; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ROS_DOMAIN_ID=0
    -D RCLC_EXECUTOR_MAX_NUMBER_OF_HANDLES=10
    -D RMW_UXRCE_MAX_NODES=10
    -D RMW_UXRCE_MAX_PUBLISHERS=10
    -D RMW_UXRCE_MAX_SUBSCRIBERS=10

board_microros_transport = serial
board_microros_distro = jazzy
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/usn-argentum/janus.git
    https://github.com/usn-argentum/hermes.git
    bakercp/PacketSerial@^1.4.0

;monitor_port = /dev/ttyACM0